"""migration v2

Revision ID: 726a6bfe759e
Revises: ff845e45362c
Create Date: 2024-08-18 01:57:47.868755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a6bfe759e'
down_revision = 'ff845e45362c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
