"""initial migration v1

Revision ID: 7e57aaf02b72
Revises: 916f9a57401f
Create Date: 2024-08-23 01:08:44.442284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e57aaf02b72'
down_revision = '916f9a57401f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credits_payment_id_payments', type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_payments_credit_id_credits'), 'credits', ['credit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_credit_id_credits'), type_='foreignkey')
        batch_op.drop_column('credit_id')

    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_credits_payment_id_payments', 'payments', ['payment_id'], ['id'])

    # ### end Alembic commands ###
